name: Checklist Workflow

on:
  push: # Trigger the workflow when code is pushed
    branches:
      - main
  schedule:
    - cron: "23 3 * * 1-5" # Runs every weekday (Mon-Fri) at 03:23 AM UTC

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: Checklist Workflow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/pom-framework/daily_checklist

      # Upload Cypress Screenshots on Test Failures
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: always() # Ensures it runs even if tests fail
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 15 # Retain artifacts for 30 days
          if-no-files-found: ignore

      # Upload Cypress Videos
      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 15 # Retain artifacts for 30 days
          if-no-files-found: ignore

      # Upload HTML Report
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: html-report
          path: cypress/reports/html/index.html
          retention-days: 15 # Retain artifacts for 30 days
          if-no-files-found: ignore
