name: Checklist Workflow

# Triggers for the workflow
on:
  push: # Trigger the workflow when code is pushed to the repository
    branches:
      - main # Run the workflow only for pushes to the 'main' branch
  schedule:
    - cron: "23 3 * * 1-5" # Schedule the workflow to run every weekday (Mon-Fri) at 03:23 AM UTC

jobs:
  cypress-run: # Job name for running the Cypress tests
    runs-on: ubuntu-22.04 # Specify the environment where the job will run
    name: Checklist Workflow

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4
        # Fetches the latest code from the repository for running the tests

      # Step 2: Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome # Specify the browser to run the tests (Chrome in this case)
          spec: cypress/e2e/pom-framework/daily_checklist # Path to the test specifications
          headless: true # Run tests in headless mode to reduce resource usage
          experimentalMemoryManagement: true # Enable experimental memory management to handle large test loads
          numTestsKeptInMemory: 5 # Limit the number of tests stored in memory to reduce crashes

      # Step 3: Upload screenshots for failed Cypress tests
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: always() # Ensure this step runs even if tests fail
        with:
          name: cypress-screenshots # Name for the uploaded artifact
          path: cypress/screenshots # Path to the directory containing screenshots
          retention-days: 15 # Retain uploaded artifacts for 15 days
          if-no-files-found: ignore # Ignore the step if no screenshots are found

      # Step 4: Upload videos for Cypress test runs
      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        if: always() # Ensure this step runs even if tests fail
        with:
          name: cypress-videos # Name for the uploaded artifact
          path: cypress/videos # Path to the directory containing videos
          retention-days: 15 # Retain uploaded artifacts for 15 days
          if-no-files-found: ignore # Ignore the step if no videos are found

      # Step 5: Upload the HTML report generated by Cypress
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always() # Ensure this step runs even if tests fail
        with:
          name: html-report # Name for the uploaded artifact
          path: cypress/reports/html/index.html # Path to the HTML report
          retention-days: 15 # Retain uploaded artifacts for 15 days
          if-no-files-found: ignore # Ignore the step if the HTML report is not found
